import type { AdoptionPetCardData } from "@/components/pet/AdoptionPetCard";
import { getPetDetailsRoute } from "@/constants/routes";

const sharedImageSrc = "/images/mock-img.png";

export const mockAvailablePets: AdoptionPetCardData[] = [
  {
    name: "Maks",
    location: "Poltava",
    size: "M",
    weightKg: 26,
    ageLabel: "2 years",
    imageSrc: sharedImageSrc,
    imageAlt: "Maks the dog sitting outdoors with a flower in his mouth",
    detailsHref: getPetDetailsRoute("mock-pet-maks"),
  },
  {
    name: "Luna",
    location: "Kyiv",
    size: "S",
    weightKg: 9,
    ageLabel: "1 year",
    imageSrc: sharedImageSrc,
    imageAlt: "Luna the dog waiting for adoption",
    detailsHref: getPetDetailsRoute("mock-pet-luna"),
  },
  {
    name: "Rocky",
    location: "Lviv",
    size: "L",
    weightKg: 31,
    ageLabel: "4 years",
    imageSrc: sharedImageSrc,
    imageAlt: "Rocky the dog waiting for adoption",
    detailsHref: getPetDetailsRoute("mock-pet-rocky"),
  },
  {
    name: "Mila",
    location: "Odesa",
    size: "M",
    weightKg: 18,
    ageLabel: "3 years",
    imageSrc: sharedImageSrc,
    imageAlt: "Mila the dog waiting for adoption",
    detailsHref: getPetDetailsRoute("mock-pet-mila"),
  },
    {
    name: "Max",
    location: "Poltava",
    size: "M",
    weightKg: 26,
    ageLabel: "2 years",
    imageSrc: sharedImageSrc,
    imageAlt: "Maks the dog sitting outdoors with a flower in his mouth",
    detailsHref: getPetDetailsRoute("mock-pet-maks"),
  },
  {
    name: "Lea",
    location: "Kyiv",
    size: "S",
    weightKg: 9,
    ageLabel: "1 year",
    imageSrc: sharedImageSrc,
    imageAlt: "Luna the dog waiting for adoption",
    detailsHref: getPetDetailsRoute("mock-pet-luna"),
  },
  {
    name: "Rock",
    location: "Lviv",
    size: "L",
    weightKg: 31,
    ageLabel: "4 years",
    imageSrc: sharedImageSrc,
    imageAlt: "Rocky the dog waiting for adoption",
    detailsHref: getPetDetailsRoute("mock-pet-rocky"),
  },
  {
    name: "Sara",
    location: "Odesa",
    size: "M",
    weightKg: 18,
    ageLabel: "3 years",
    imageSrc: sharedImageSrc,
    imageAlt: "Mila the dog waiting for adoption",
    detailsHref: getPetDetailsRoute("mock-pet-mila"),
  },
];
